stages:
  train:
    cmd: python train.py  # если основной скрипт
    deps:
      - iris_data.csv
      - train.py
    outs:
      - metrics.json

  train_modified:
    cmd: python train_modified.py
    deps:
      - iris_data.csv
      - train_modified.py
    outs:
      - metrics_modified.json

  metrics_and_plots:
    cmd: python metrics_and_plots.py
    deps:
      - metrics.json
      - metrics_modified.json
      - iris_data.csv
    outs:
      - baseline_metrics_graph.png
      - correlation_matrix.png
      - modified_metrics_graph.png
